version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@edutechdb_high?TNS_ADMIN=/microEvaluacion/Wallet
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=DuocUc..2025
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=oracle.jdbc.OracleDriver
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.OracleDialect
    depends_on:
      - db

  db:
    image: gvenzl/oracle-free:23.3.0
    container_name: oracle-db
    environment:
      - ORACLE_PASSWORD=DuocUc..2025
      - APP_USER=admin
      - APP_USER_PASSWORD=DuocUc..2025
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata

volumes:
  oracle-data: